### ISSUE TITLE
Hiya, I'm having trouble configuring your widget, can I trouble you to help me out, please?

### ISSUE THREAD

**Issue by JMarkyBB** [illuminati945/ToDo#1]
Can you help me from here illuminati945 please?

![screenshot 2017-04-25 13 36 05](https://cloud.githubusercontent.com/assets/27829143/25385534/4dfa2046-29bc-11e7-8cf9-38f6bf7aa953.png)

**Comment by illuminati945** [comment]
Hey JMarkeyBB, you need to create a .txt file (which is going to be your todo list) and then link it in the code. to access the code simply open the .coffee file. tell me if that works :)

**Comment by JMarkyBB** [comment]
Hiya illuminati945,

Thanks for your reply, its appreciated, I am back in touch because I'm all new to this and coding, but I love the idea of it, so I'm going to give it a go. Do I create the .txt file in the Command Terminal, or in Text Editor, sorry for the inexperience.

**Comment by illuminati945** [comment]
All good. Just open textedit and create a new file, saving it as a .txt wherever you want. then, link \ the file you made in the code.

**Comment by JMarkyBB** [comment]
Ok, cheers.

will have a go.

**Comment by illuminati945** [comment]
Sweet, tell my how it goes

**Comment by illuminati945** [comment]
Can I close the issue?

**Comment by JMarkyBB** [comment]
I've not had chance to have a go yet lluminati945, (life & sh**) but yes, close the issue, I'm sure it will work.
