### ISSUE TITLE
Can You help me to configure this widget please

### ISSUE THREAD

**Issue by JMarkyBB** [illuminati945/ToDo#2]
I'm having trouble configuring this ToDo widget, if its not to much trouble illuminati945.

![screen shot 2017-10-11 at 1 06 25 pm](https://user-images.githubusercontent.com/27829143/31439702-12ef2228-ae85-11e7-868a-7f5eaed38116.png)

**Comment by ByteGui** [comment]
Hey, I think I can help you! When you create your todo list on textEdit, you have to convert to .txt in "format".  It solve my issue. I hope it helps

**Comment by illuminati945** [comment]
yeet
